#define CONST 1
#define INT 2
#define FLOAT 3
#define STRING 4
#define CHAR 5
#define BOOL 6
#define IF 7
#define THEN 8
#define WHILE 9
#define FOR 10
#define SWITCH 11
#define CASE 12
#define DO 13
#define DEFAULT 14
#define ELIF 15
#define ELSE 16
#define RETURN 17
#define MAIN 18
#define INCLUDE 19
#define HASH 20
#define SINGLE_QUOTE 21
#define DOUBLE_QUOTE 22
#define SEMI_COLON 23
#define OPENED_BRACKET 24
#define CLOSED_BRACKET 25
#define OPENED_BRACE 26
#define CLOSED_BRACE 27
#define OPENED_SQ_BRACKET 28
#define CLOSED_SQ_BRACKET 29
#define COMMA 30
#define TWO_DOTS 31
#define AND 32
#define EQUAL_EQUAL 33
#define OR 34
#define VOID 35
#define NOT_EQUAL 36
#define GREATER_THAN 37
#define GREATER_THAN_EQUAL 38
#define SMALLER_THAN_EQUAL 39
#define SMALLER_THAN 40
#define NOT 41
#define PLUS 42
#define MINUS 43
#define MULTIPLY 44
#define DIVIDE 45
#define REMAINDER 46
#define PLUS_EQUAL 47
#define MINUS_EQUAL 48
#define DIVIDE_EQUAL 49
#define MULTIPLY_EQUAL 50
#define PLUS_PLUS 51
#define MINUS_MINUS 52
#define EQUAL 53
#define COMMENT 54
#define IDENTIFIER 55
